import type { Metadata } from 'next'
import './_styles/globals.scss'
import localFont from 'next/font/local'
import style from './_styles/layout.module.scss'
import QueryProvider from './_components/reactQuery/QueryProvider'
import LoginCheckProvider from './_api/LoginCheckProvider'
import Script from 'next/script'
import RecoilProvider from './_recoil/RecoilProvider'

const pretendard = localFont({
  src: [
    {
      path: './_styles/fonts/Pretendard-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './_styles/fonts/Pretendard-SemiBold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './_styles/fonts/Pretendard-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './_styles/fonts/Pretendard-Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Script src="https://cdn.iamport.kr/v1/iamport.js" />
      <body className={pretendard.className}>
        <div className={style.container}>
          <QueryProvider>
            <RecoilProvider>
              <LoginCheckProvider>{children}</LoginCheckProvider>
            </RecoilProvider>
          </QueryProvider>
        </div>
        {modal}
      </body>
    </html>
  )
}
