import type { Metadata } from 'next'
import './_styles/globals.scss'
import localFont from 'next/font/local'
import style from './_styles/layout.module.scss'
import QueryProvider from './_components/reactQuery/QueryProvider'

const pretendard = localFont({
  src: [
    {
      path: './_styles/fonts/Pretendard-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './_styles/fonts/Pretendard-SemiBold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './_styles/fonts/Pretendard-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './_styles/fonts/Pretendard-Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <div className={style.container}>
          <QueryProvider> {children}</QueryProvider>
        </div>
      </body>
    </html>
  )
}
